backend:
  name: github
  repo: https://github.com/parthpatoliya97/svelte-cms
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "Home"
    label: "Home"
    create: true
    files:
      - label: "Home"
        name: "Home"
        file: "content/home.json"
        fields:
          - label: "metaTags"
            name: "meta"
            widget: "object"
            fields:
              - { label: "slug", name: "slug", widget: "string" }
              - { label: "pageTitle", name: "pageTitle", widget: "string" }
              - { label: "metaTitle", name: "metaTitle", widget: "string" }
              - { label: "MetaDescription", name: "description", widget: "text" }
          
          - label: "hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Background Color", name: "bgColor", widget: "string" }
             
              - label: "ctas"
                name: "ctas"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
                  - { label: "Is Primary", name: "isPrimary", widget: "boolean" }

          - label: "logos"
            name: "logos"
            widget: "object"
            fields:
              - {label: "Title",name: "title",widget: "string"}
              - {label: "Description",name: "description",widget: "text"}
              - { label: "Background Color", name: "bgColor", widget: "string" }
              - label: "images"
                name: "images"
                widget: "list"
                fields:
                  - {label: "image",name: "src",widget: "image"}
                  - {label: "altText",name: "alt",widget: "string"}

          - label: "services"
            name: "services"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "text"}
                  - { label: "Background Color", name: "bgColor", widget: "string" }
                  - {label: "target",name: "target",widget: "text"}
                  - {label: "icon",name: "icon",widget: "image"}

          - label: "products"
            name: "products"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "text"}
                  - {label: "image",name: "image",widget: "image"}
                  - {label: "altText",name: "alt",widget: "string"}
                  - {label: "target",name: "target",widget: "string"}

          - label: "Tech"
            name: "Tech"
            widget: "object"
            fields:
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "image",name: "image",widget: "string"}
                  - {label: "altText",name: "alt",widget: "string"}

          - label: "stats"
            name: "stats"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - {label: "bgImage",name: "bgImage",widget: "image"}
              - {label: "altText",name: "altText",widget: "string"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "string"}

          - label: "worldDominance"
            name: "worldDominance"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - {label: "bgImage",name: "bgImage",widget: "image"}
              - {label: "altText",name: "alt",widget: "string"}

          - label: "showcase"
            name: "showcase"
            widget: "object"
            fields:
              - label: "images"
                name: "images"
                widget: "list"
                fields:
                  - {label: "image",name: "image",widget: "image"}
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Background Color", name: "bgColor", widget: "string" }

          - label : "industries"
            name: "industries"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "text"}
                  - {label: "target",name: "target",widget: "string"}
                  - { label: "bhColor", name: "bgColor", widget: "string" }
                  - {label: "icon",name: "icon",widget: "image"}

          - label: "whyChooseUs"
            name: "whyChooseUs"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - {label: "bgColor", name: "bgColor", widget: "string"}
              - label: "demoImages"
                name: "demoImages"
                widget: "list"
                fields:
                  - {label: "demoImage",name: "image",widget: "image"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "ID",name: "id",widget: "number"}
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "text"}
                  - {label: "bgColor", name: "bgColor", widget: "string"} 

          - label : "testimonials"
            name : "testimonials"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - {label: "bgColor", name: "bgColor", widget: "string"}
              - label: "data"
                name: "data"
                widget: "list"
                fields: 
                  - {label: "ID",name: "id",widget: "number"}
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "text"}
                  - {label: "image",name: "image",widget: "image"}

          - label: "coreValues"
            name: "coreValues"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "description",name: "description",widget: "text"}
                  - {label: "bgColor", name: "bgColor", widget: "string"}
                  - {label: "icon",name: "icon",widget: "image"}

          - label: "compliance"
            name: "compliance"
            widget: "object"
            fields:
              - {label: "gdpr",name: "gdpr",widget: "string"}

          - label: "faq"
            name: "faq"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "icon",name: "icon",widget: "image"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "FAQ questions and Answers"
                name: "qa"
                widget: "list"
                fields:
                  - {label: "question",name: "question",widget: "string"}
                  - {label: "answer",name: "answer",widget: "text"}

          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - { label: "Primary Button Title", name: "primaryButtonTitle", widget: "string" }
              - { label: "Primary Button Target", name: "primaryButtonTarget", widget: "string" }
              - { label: "Secondary Button Title", name: "secondaryButtonTitle", widget: "string" }
              - { label: "Secondary Button Target", name: "secondaryButtonTarget", widget: "string" }

          - label : "blogs"
            name : "blogs"
            widget: "object"
            fields:
              - {label: "label",name: "label",widget: "string"}
              - {label: "title",name: "title",widget: "string"}
              - {label: "description",name: "description",widget: "text"}
              - label: "data"
                name: "data"
                widget: "list"
                fields:
                  - {label: "image",name: "image",widget: "image"}
                  - {label: "altText",name: "alt",widget: "text"}
                  - {label: "date",name: "date",widget: "date"}
                  - {label: "display date",name: "dateDisplay",widget: "string"}
                  - {label: "category",name: "category",widget: "string"}
                  - {label: "title",name: "title",widget: "string"}
                  - {label: "target",name: "target",widget: "string"}
                  - {label: "excerpt",name: "excerpt",widget: "text"}
                  - label: "Author"
                    name: "author"
                    widget: "object"
                    fields:
                       - {label: "Name", name: "name", widget: "string"}
                       - {label: "Role", name: "role", widget: "string"}
                       - {label: "Target", name: "target", widget: "string"}
                       - {label: "Image", name: "image", widget: "image"}
              
  - label: "Header & Footer"
    name: "header-footer"
    create: true
    files:
      - label: "Header & Footer Content"
        name: "header-footer"
        file: "content/header-footer.json"
        fields:
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - label: "Logo"
                name: "logo"
                widget: "object"
                fields:
                  - { label: "Logo Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "altText", widget: "string" }
              - label: "Menu Items"
                name: "menuItems"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Target", name: "target", widget: "string", required: false }
                  - label: "Submenu"
                    name: "submenu"
                    widget: "list"
                    required: false
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Target", name: "target", widget: "string" }
              - label: "CTA Button"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Target", name: "target", widget: "string" }
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - label: "Logo"
                name: "logo"
                widget: "object"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
              - label: "Social Links"
                name: "socialLinks"
                widget: "list"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "Target", name: "target", widget: "string"}
                  - {label: "Icon", name: "icon", widget: "string"}
              - label: "Menu Items"
                name: "menuItems"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - label: "Submenu"
                    name: "submenu"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Target", name: "target", widget: "string"}
              - label: "Copyright"
                name: "copyright"
                widget: "string"
                fields:
                - {label: "copyright",name: "copyright",widget: "string"}