backend:
  name: github
  repo: https://github.com/parthpatoliya97/svelte-cms
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "Home"
    label: "Home Page"
    create: true
    files:
      - label: "Meta Information Section"
        name: "meta"
        file: "content/home.json"
        fields:
          - label: "Meta Configuration"
            name: "meta"
            widget: "object"
            fields:
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Page Title", name: "pageTitle", widget: "string" }
              - { label: "Meta Title", name: "metaTitle", widget: "string" }
              - { label: "Meta Description", name: "description", widget: "text" }

      - label: "Hero Section"
        name: "hero"
        file: "content/home.json"
        fields:
          - label: "Hero details"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Background Color", name: "bgColor", widget: "string" }
              - label: "CTA Buttons"
                name: "ctas"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
                  - { label: "Is Primary", name: "isPrimary", widget: "boolean" }

      - label: "Services Section"
        name: "services"
        file: "content/home.json"
        fields:
          - label: "Services details"
            name: "services"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Service Items"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Background Color", name: "bgColor", widget: "string" }
                  - { label: "Target", name: "target", widget: "text" }
                  - { label: "Icon", name: "icon", widget: "image" }

      - label: "Products Section"
        name: "products"
        file: "content/home.json"
        fields:
          - label: "Products details"
            name: "products"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Products List"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
                  - { label: "Target", name: "target", widget: "string" }

      - label: "Tech Section"
        name: "tech"
        file: "content/home.json"
        fields:
          - label: "Tech details"
            name: "tech"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Tech Images"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }

      - label: "Stats Section"
        name: "stats"
        file: "content/home.json"
        fields:
          - label: "Stats details"
            name: "stats"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Image", name: "bgImage", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - label: "Stats Data"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }

      - label: "World Dominance Section"
        name: "worldDominance"
        file: "content/home.json"
        fields:
          - label: "World Dominance details"
            name: "worldDominance"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Image", name: "bgImage", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" } 

      - label: "Showcase Section"
        name: "showcase"
        file: "content/home.json"
        fields:
          - label: "Showcase details"
            name: "showcase"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Background Color", name: "bgColor", widget: "string" }
              - label: "Showcase Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }

      - label: "Industries Section"
        name: "industries"
        file: "content/home.json"
        fields:
          - label: "Industries details"
            name: "industries"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Industries List"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Target", name: "target", widget: "string" }
                  - { label: "Background Color", name: "bgColor", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "image" }

      - label: "Why Choose Us Section"
        name: "whyChooseUs"
        file: "content/home.json"
        fields:
          - label: "Why Choose Us details"
            name: "whyChooseUs"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Color", name: "bgColor", widget: "string" }
              - label: "Demo Images"
                name: "demoImages"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
              - label: "Features List"
                name: "data"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "number" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Background Color", name: "bgColor", widget: "string" }

      - label: "Testimonials Section"
        name: "testimonials"
        file: "content/home.json"
        fields:
          - label: "Testimonials details"
            name: "testimonials"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Color", name: "bgColor", widget: "string" }
              - label: "Testimonials List"
                name: "data"
                widget: "list"
                fields:
                  - { label: "ID", name: "id", widget: "number" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Image", name: "image", widget: "image" }

      - label: "Core Values Section"
        name: "coreValues"
        file: "content/home.json"
        fields:
          - label: "Core Values details"
            name: "coreValues"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Values List"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Background Color", name: "bgColor", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "image" }

      - label: "Compliance Section"
        name: "compliance"
        file: "content/home.json"
        fields:
          - label: "Compliance details"
            name: "compliance"
            widget: "object"
            fields:
              - { label: "GDPR", name: "gdpr", widget: "string" }

      - label: "FAQ Section"
        name: "faq"
        file: "content/home.json"
        fields:
          - label: "FAQ details"
            name: "faq"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Icon", name: "icon", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Color", name: "bgColor", widget: "string" }
              - label: "Questions and Answers"
                name: "qa"
                widget: "list"
                fields:
                  - { label: "Question", name: "question", widget: "string" }
                  - { label: "Answer", name: "answer", widget: "string" }

      - label: "CTA Section"
        name: "cta"
        file: "content/home.json"
        fields:
          - label: "CTA details"
            name: "cta"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Primary Button Title", name: "primaryButtonTitle", widget: "string" }
              - { label: "Primary Button Target", name: "primaryButtonTarget", widget: "string" }
              - { label: "Secondary Button Title", name: "secondaryButtonTitle", widget: "string" }
              - { label: "Secondary Button Target", name: "secondaryButtonTarget", widget: "string" }

      - label: "Blogs Section"
        name: "blogs"
        file: "content/home.json"
        fields:
          - label: "Blogs details"
            name: "blogs"
            widget: "object"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Blog Posts"
                name: "data"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "text" }
                  - { label: "Date", name: "date", widget: "date" }
                  - { label: "Display Date", name: "dateDisplay", widget: "string" }
                  - { label: "Category", name: "category", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Target", name: "target", widget: "string" }
                  - { label: "Excerpt", name: "excerpt", widget: "text" }
                  - label: "Author"
                    name: "author"
                    widget: "object"
                    fields:
                      - { label: "Name", name: "name", widget: "string" }
                      - { label: "Role", name: "role", widget: "string" }
                      - { label: "Target", name: "target", widget: "string" }
                      - { label: "Image", name: "image", widget: "image" }




              
  - label: "Header & Footer"
    name: "header-footer"
    create: true
    files:
      - label: "Header Section"
        name: "header"
        file: "content/header-footer.json"
        fields:
          - label: "Header details"
            name: "header"
            widget: "object"
            fields:
              - label: "Logo"
                name: "logo"
                widget: "object"
                fields:
                  - { label: "Logo Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "altText", widget: "string" }
              - label: "Menu Items"
                name: "menuItems"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Target", name: "target", widget: "string", required: false }
                  - label: "Submenu"
                    name: "submenu"
                    widget: "list"
                    required: false
                    fields:
                      - { label: "Title", name: "title", widget: "string" }
                      - { label: "Target", name: "target", widget: "string" }
              - label: "CTA Button"
                name: "cta"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Target", name: "target", widget: "string" }
      - label: "Footer Section"
        name: "footer"
        file: "content/header-footer.json"
        fields:
          - label: "Footer details"
            name: "footer"
            widget: "object"
            fields:
              - label: "Logo"
                name: "logo"
                widget: "object"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Alt Text", name: "alt", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
              - label: "Social Links"
                name: "socialLinks"
                widget: "list"
                fields:
                  - {label: "Label", name: "label", widget: "string"}
                  - {label: "Target", name: "target", widget: "string"}
                  - {label: "Icon", name: "icon", widget: "string"}
              - label: "Menu Items"
                name: "menuItems"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - label: "Submenu"
                    name: "submenu"
                    widget: "list"
                    fields:
                      - {label: "Title", name: "title", widget: "string"}
                      - {label: "Target", name: "target", widget: "string"}
              - label: "Copyright"
                name: "copyright"
                widget: "string"
                fields:
                - {label: "copyright",name: "copyright",widget: "string"}



  
              
              
   